language: go

sudo: false

git:
  depth: 3

os:
  - linux

services:
  - nginx
  - postgresql

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

addons:
  apt:
    packages:
      - nginx
      - rpm

install: true

before_script:
  - make clean

script:
  - make rpm-build
