language: go

sudo: false

git:
  depth: 3

os:
  - linux

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

addons:
  postgresql: "9.4"
  apt:
    packages:
      - nginx
      - rpm
      - geoip-bin
      - geoip-database

install: true

before_script:
  - make clean

script:
  - make rpm-build
