language: go

sudo: false

git:
  depth: 3

os:
  - linux

services:
  - apache
  - postgresql

env:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8

addons:
  apt:
    packages:
      - apache2
      - rpm

install: true

before_script:
  - make clean

script:
  - make rpm-build
