FROM centos:centos7
MAINTAINER Sergio Visinoni <piffio@piffio.org>

RUN yum install -y bzip2 fontconfig

ENV PHANTOMJS_VER 2.1.1-linux-x86_64

RUN curl -sSL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-$PHANTOMJS_VER.tar.bz2 | tar jxC /
RUN ln -s /phantomjs-$PHANTOMJS_VER/bin/phantomjs /usr/bin/phantomjs
RUN mkdir -p /scripts && ln -s /phantomjs-$PHANTOMJS_VER/examples /scripts/phantomjs
COPY bin/kool-agent /
COPY conf/kool-agent*.conf /

ENTRYPOINT [ "/kool-agent", "-conf"]
CMD [ "/kool-agent-docker.conf" ]
