#!/bin/bash

files=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
[ -z "$files" ] && exit 0

unformatted=$(gofmt -l $gofiles)
[ -z "$unformatted" ] && exit 0

echo >&2 "Go files must be formatted with gofmt. Please run:"

for fn in $unformatted; do
	echo >&2 "  gofmt -w $PWD/$fn"
done

exit 1

